name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip3 install .[dev]

    - name: Run --help
      run: oj-api -h

    - name: Run pylint
      run: pylint --rcfile=setup.cfg onlinejudge onlinejudge_api tests setup.py

    - name: Run isort
      run: isort --check-only --diff onlinejudge onlinejudge_api tests setup.py

    - name: Run yapf
      run: yapf --diff --recursive onlinejudge onlinejudge_api tests setup.py

    - name: Run mypy
      run: mypy onlinejudge onlinejudge_api tests setup.py
