# This file is a workaround for the problem about "Re-run jobs" https://github.community/t5/GitHub-Actions/Ability-to-rerun-just-a-single-job-in-a-workflow/m-p/41629

name: test-unstable-workaround

on: [pull_request]

jobs:
  test-unstable-workaround:
    strategy:
      matrix:
        os: [macos-latest]
        pattern: [unstable]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Get pip cache
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip3 install --upgrade setuptools
        pip3 install .[dev]

    - name: Load balancing
      id: load-balancing
      run: |
          python -m tests.load_balancer ${{ matrix.pattern }}

    - name: Run tests
      run: |
        oj-api -h
        pytest -v ${{ steps.load-balancing.outputs.files }}
