name: test

on:
  pull_request:
  schedule:
    - cron: '30 18 * * MON'  # At 03:30 on Tuesday in JST

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
        pattern: [stable]  # see test-unstable-workaround-*.yml



    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get pip cache
      id: pip-cache
      shell: python
      run: |
        from pip._internal.locations import USER_CACHE_DIR
        import os
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          print('dir=' + USER_CACHE_DIR)
          print('dir=' + USER_CACHE_DIR, file=f)

    - uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip3 install --upgrade setuptools
        pip3 install .[dev]

    # see https://github.com/online-judge-tools/oj/issues/755<Paste>
    - name: Workaround for the conflict of the module name
      run: bash workaround_for_conflict.sh

    - name: Load balancing
      id: load-balancing
      run: |
          python -m tests_workaround_for_conflict.load_balancer ${{ matrix.pattern }}

    - name: Run tests
      run: |
        oj-api -h
        pytest -v ${{ steps.load-balancing.outputs.files }}
      env:
        ATCODER_USERNAME: ${{ secrets.ATCODER_USERNAME }}
        ATCODER_PASSWORD: ${{ secrets.ATCODER_PASSWORD }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        CODEFORCES_USERNAME: ${{ secrets.CODEFORCES_USERNAME }}
        CODEFORCES_PASSWORD: ${{ secrets.CODEFORCES_PASSWORD }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
